In [1]:
# 필요 라이브러리 import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv("./data/8-1 train(std).csv",index_col=0)
test1 = pd.read_csv("./data/8-1 test1(std).csv",index_col=0)
test2 = pd.read_csv("./data/8-1 test2(std).csv",index_col=0)


In [3]:
x_train = train.drop("label",axis=1)
y_train = train["label"]
x_test =test2.drop("label",axis=1)
y_test = test2["label"]

In [4]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

In [5]:
# 1-1 LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(x_train, y_train)
lda_pred = lda_clf.predict(x_test)
lda_pred_proba = lda_clf.predict_proba(x_test)

In [6]:
print("lda") 
print(get_clf_eval(y_test, lda_pred))

lda
오차행렬
[[2124   57]
 [  15    7]]
정확도: 0.9673, 정밀도 : 0.1094, 재현율:0.3182,F1 스코어:0.1628
ROC 스코어: 0.6460, PR score : 0.0416
None


In [7]:
# 디시전트리 구현
from sklearn.tree import DecisionTreeClassifier 
dt_clf = DecisionTreeClassifier(random_state=52)     
dt_clf.fit(x_train, y_train)
dt_pred = dt_clf.predict(x_test)
dt_pred_proba = dt_clf.predict_proba(x_test)                                    

In [8]:
print("디시전트리") 
print(get_clf_eval(y_test, lda_pred))

디시전트리
오차행렬
[[2124   57]
 [  15    7]]
정확도: 0.9673, 정밀도 : 0.1094, 재현율:0.3182,F1 스코어:0.1628
ROC 스코어: 0.6460, PR score : 0.0416
None


In [9]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=52)     
rf_clf.fit(x_train, y_train)
rf_pred = rf_clf.predict(x_test)
rf_pred_proba = rf_clf.predict_proba(x_test)

In [10]:
print("랜덤포레스트") 
get_clf_eval(y_test, rf_pred)

랜덤포레스트
오차행렬
[[2173    8]
 [  20    2]]
정확도: 0.9873, 정밀도 : 0.2000, 재현율:0.0909,F1 스코어:0.1250
ROC 스코어: 0.5436, PR score : 0.0273


In [11]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(x_train, y_train)
lr_pred = lr_clf.predict(x_test)
lr_pred_proba = lr_clf.predict_proba(x_test)

In [12]:
print("로지스틱") 
get_clf_eval(y_test, lr_pred)

로지스틱
오차행렬
[[2170   11]
 [  18    4]]
정확도: 0.9868, 정밀도 : 0.2667, 재현율:0.1818,F1 스코어:0.2162
ROC 스코어: 0.5884, PR score : 0.0567
